version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/plugin"
    schedule:
      interval: "weekly"