name-template: '$NEXT_PATCH_VERSION'   # 默认草稿 release 名称模板（可被 workflow 覆盖）
tag-template: '$NEXT_PATCH_VERSION'    # 默认 tag 模板（可被 workflow 覆盖）
version-template: '$MAJOR.$MINOR.$PATCH' # 计算下一个版本时使用的格式（保留默认）

no-changes-template: |
  * No changes

change-template: '* $TITLE (#$NUMBER) by @$AUTHOR'

# 发布说明的主体模板
template: |
  ## What's Changed
  
  $CHANGES

# 按 PR label 把变更分组，title 是在 Release Notes 中显示的分组标题
categories:
  - title: 'Added'
    label: 'feature'
  - title: 'Changed'
    label: 'enhancement'
  - title: 'Fixed'
    label: 'bug'
  - title: 'Security'
    label: 'security'
  - title: 'Deprecated'
    label: 'deprecation'
  - title: 'Removed'
    label: 'removed'
  - title: 'Documentation'
    label: 'documentation'
  - title: 'Misc'
    label: 'chore'

sort-by: merged_at
sort-direction: descending

exclude-labels:
  - 'no-changelog'
  - 'skip-changelog'

exclude-contributors:
  - dependabot[bot]
  - github-actions[bot]
