name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Gradle ShadowJar
        run: ./gradlew clean :plugin:shadowJar
        env:
          GPR_USER: ${{ github.actor }}
          GPR_KEY: ${{ secrets.GPR_KEY }}

      - name: List built artifacts (debug)
        run: ls -la plugin/build/libs || true

      - name: Detect release channel
        id: channel
        run: |
          ver="${VERSION,,}"
          if [[ "$ver" == *"alpha"* ]]; then
            echo "value=alpha" >> $GITHUB_OUTPUT
          elif [[ "$ver" == *"beta"* ]]; then
            echo "value=beta" >> $GITHUB_OUTPUT
          else
            echo "value=release" >> $GITHUB_OUTPUT
          fi

      - name: Extract changelog for this version
        id: changelog
        run: |
          VERSION=${VERSION#v}
          echo "Extracting changelog for $VERSION"
          awk -v ver="## $VERSION " '
            $0 ~ ver {flag=1; next}
            /^## / && flag {exit}
            flag {print}
          ' CHANGELOG.md > RELEASE_CHANGELOG.md

          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat RELEASE_CHANGELOG.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body: ${{ steps.changelog.outputs.body }}
          generate_release_notes: false
          files: |
            plugin/build/libs/HyphaShop-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: SeLGgTIu
          name: ${{ env.VERSION }}
          version: ${{ env.VERSION }}
          changelog: ${{ steps.changelog.outputs.body }}
          channel: ${{ steps.detect-channel.outputs.channel }}
          loaders: |-
            paper
            folia
            purpur
          game-versions: '[1.21.x]'
          files: plugin/build/libs/HyphaShop-*.jar
